import { ACCENT, ACCENT_BRIGHT } from "../data/portfolioData";

export const styles = {
  appWrap: {
    background: "#0a0a0a",
    color: "#fff",
    fontFamily: "'Inter', sans-serif",
    width: "100vw",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    position: "fixed",
    top: 0,
    left: 0,
  },
  app: {
    display: "flex",
    gap: 8,
    padding: 8,
    flex: 1,
    minHeight: 0,
  },
  sidebar: {
    background: "#000",
    borderRadius: 12,
    padding: "20px 12px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    overflow: "hidden",
    flexShrink: 0,
    minWidth: 76,
  },
  resizeHandle: {
    position: "absolute",
    top: 0,
    right: -4,
    width: 8,
    height: "100%",
    cursor: "col-resize",
    zIndex: 30,
    background: "transparent",
  },
  collapseBtn: {
    position: "absolute",
    top: 10,
    right: 8,
    width: 26,
    height: 26,
    borderRadius: 6,
    background: "transparent",
    border: "none",
    color: "#727272",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    zIndex: 10,
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px 20px",
    background: "transparent",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
  },
  brandMark: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    background: ACCENT,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontFamily: "Montserrat",
    fontWeight: 900,
    color: "#000",
    fontSize: 15,
    flexShrink: 0,
  },
  brandName: {
    fontFamily: "Montserrat",
    fontWeight: 800,
    fontSize: 16,
    lineHeight: 1.1,
    color: "#fff",
  },
  brandRole: {
    fontSize: 11,
    color: "#a7a7a7",
    fontFamily: "JetBrains Mono",
  },
  topbarMobileActionsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  topbarMobileBrand: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 0,
    minWidth: 0,
    flexShrink: 1,
  },
  topbarMobileBrandText: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    minWidth: 0,
  },
  topbarMobileBrandName: {
    fontSize: 13.5,
    fontWeight: 700,
    color: "#fff",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "100%",
  },
  topbarMobileBrandRole: {
    fontSize: 10.5,
    fontWeight: 500,
    color: "#727272",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "100%",
  },
  topbarMobileBrandMark: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    background: ACCENT,
    color: "#000",
    fontSize: 12,
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    padding: "10px 14px",
    borderRadius: 10,
    border: "none",
    background: "transparent",
    color: "#a7a7a7",
    fontSize: 13.5,
    fontWeight: 600,
    cursor: "pointer",
    position: "relative",
    transition: "background .15s ease, color .15s ease",
    textAlign: "left",
  },
  navItemHover: {
    background: ACCENT,
    color: "#fff",
  },
  navItem: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    padding: "10px 14px",
    borderRadius: 10,
    border: "none",
    background: "transparent",
    color: "#a7a7a7",
    fontSize: 13.5,
    fontWeight: 600,
    cursor: "pointer",
    position: "relative",
    transition: "background .15s ease, color .15s ease",
    textAlign: "left",
  },
  navItemHover: {
    background: "rgba(255,255,255,0.06)",
    color: "#fff",
  },
  navItemActive: {
    background: "#282828",
    color: "#fff",
  },
  navItemActiveBar: {
    position: "absolute",
    left: 0,
    top: "50%",
    transform: "translateY(-50%)",
    width: 3,
    height: 18,
    borderRadius: 999,
    background: ACCENT,
  },
  ctaPrimaryHover: {
    background: ACCENT_BRIGHT,
    transform: "translateY(-2px)",
    boxShadow: "0 8px 20px rgba(29,185,84,0.35)",
  },
  ctaSecondaryHover: {
    background: "rgba(255,255,255,0.1)",
    borderColor: "rgba(255,255,255,0.3)",
    transform: "translateY(-2px)",
  },
  mobileTopBar: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    height: 56,
    background: "#181818",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    alignItems: "center",
    padding: "0 16px",
    zIndex: 100,
  },
  mobileBrand: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    padding: 0,
  },
  mobileBrandName: {
    fontSize: 14,
    fontWeight: 700,
    color: "#fff",
  },
  mobileBottomNav: {
    position: "fixed",
    bottom: 0,
    left: 0,
    right: 0,
    height: 64,
    background: "#181818",
    borderTop: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-around",
    zIndex: 100,
    paddingBottom: "env(safe-area-inset-bottom, 0px)",
  },
  mobileNavItem: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    flex: 1,
    height: "100%",
  },
  mobileNavLabel: {
    fontSize: 10,
    fontWeight: 600,
  },
  mobileNavDot: {
    position: "absolute",
    top: 4,
    width: 4,
    height: 4,
    borderRadius: "50%",
    background: "#1db954",
  },
  main: {
    background: "#121212",
    flex: 1,
    minWidth: 0,
    borderRadius: 12,
    overflowY: "auto",
    position: "relative",
  },
  topbar: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 32px",
    backdropFilter: "blur(10px)",
    background: "rgba(10,10,10,0.4)",
  },
  topbarMobileWrap: {
    position: "sticky",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: "14px 16px",
    background: "linear-gradient(180deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.3) 65%, rgba(0,0,0,0) 100%)",
    backdropFilter: "blur(6px)",
    WebkitBackdropFilter: "blur(6px)",
  },
  topbarMobileActionsRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  topbarMobileSocials: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  topbarMobileName: {
    fontSize: 14,
    fontWeight: 700,
    color: "#fff",
  },
  searchBox: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    backgroundColor: "rgba(29,185,84,0.08)",
    color: ACCENT_BRIGHT,
    boxShadow: "0 0 0 1px rgba(29,185,84,0.35), 0 0 16px rgba(29,185,84,0.25)",
    borderRadius: 24,
    padding: "9px 16px",
    width: 300,
  },
  searchInput: {
    background: "transparent",
    border: "none",
    outline: "none",
    color: "#fff",
    fontSize: 13.5,
    width: "100%",
    fontFamily: "inherit",
  },
  btnPill: {
    background: ACCENT,
    color: "#fff",
    fontWeight: 800,
    fontSize: 14,
    padding: "11px 28px",
    borderRadius: 12,
    border: "none",
    cursor: "pointer",
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  hero: {
    display: "flex",
    alignItems: "flex-end",
    gap: 28,
    padding: "40px 32px 28px",
    position: "relative",
    paddingTop: 56 + 14,
    flexWrap: "wrap",
  },
  heroMobile: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    gap: 16,
    padding: "40px 20px 32px",
    position: "relative",
  },
  heroInfoMobile: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
  },
  heroSubMobile: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 6,
  },
  ctaRowMobile: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    marginTop: 14,
    width: "100%",
  },
  ctaPrimaryMobile: {
    width: "100%",
    justifyContent: "center",
  },
  ctaSecondaryMobile: {
    width: "100%",
    justifyContent: "center",
  },
  verifiedBadge: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    fontWeight: 700,
    color: "#fff",
  },
  verifiedIcon: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 18,
    height: 18,
    borderRadius: "50%",
    color: "#fff",
    fontSize: 10,
    marginRight: 4,
  },
  heroGlow: {
    position: "absolute",
    left: 0,
    top: -40,
    right: 0,
    height: 420,
    background: "linear-gradient(180deg, #1a2b1f 0%, rgba(26,43,31,0.4) 50%, transparent 70%)",
    zIndex: 0,
    pointerEvents: "none",
  },
  heroPhotoWrap: {
    width: 192,
    height: 192,
    borderRadius: "50%",
    overflow: "hidden",
    boxShadow: "0 12px 32px rgba(0,0,0,0.6)",
    border: "4px solid rgba(255,255,255,0.06)",
  },
  heroPhoto: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    transform: "scale(1.25)",
    transformOrigin: "center center",
  },
  heroTitle: {
    fontSize: 64,
    fontWeight: 900,
    letterSpacing: 1.5,
    margin: "8px 0 16px",
    lineHeight: 1,
    fontFamily: "Montserrat",
    position: "relative",
    zIndex: 1,
  },
  heroSub: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    color: "#a7a7a7",
    fontSize: 14,
    fontWeight: 600,
    position: "relative",
    zIndex: 1,
  },
  heroGlowAccent: {
    position: "absolute",
    left: -80,
    top: -60,
    width: 380,
    height: 380,
    background: "radial-gradient(circle, rgba(29,185,84,0.35), transparent 70%)",
    zIndex: 0,
    pointerEvents: "none",
    filter: "blur(10px)",
    transition: "all .4s ease",
  },
  heroGlowAccentHover: {
    background: "radial-gradient(circle, rgba(29,185,84,0.6), transparent 72%)",
    filter: "blur(14px)",
    transform: "scale(1.15)",
  },
  ctaPrimary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: ACCENT,
    color: "#fff",
    fontWeight: 700,
    fontSize: 14,
    padding: "12px 22px",
    borderRadius: 24,
    border: "none",
    cursor: "pointer",
    fontFamily: "inherit",
    boxShadow: "0 6px 18px rgba(29,185,84,0.3)",
    transition: "all .2s ease",
  },
  ctaSecondary: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    background: "transparent",
    color: "#fff",
    fontWeight: 700,
    fontSize: 14,
    padding: "12px 22px",
    borderRadius: 24,
    border: "1px solid #2a2a2a",
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all .2s ease",
  },
  section: {
    padding: "0 32px",
    scrollMarginTop: 72,
    marginBottom: 32,
  },
  bioPanel: {
    display: "grid",
    gridTemplateColumns: "1.5fr 1fr",
    gap: 28,
    padding: "6px 0 6px",
    justifyContent: "space-between",
    color: "#d6d6d6",
    fontSize: 12,
    lineHeight: 1,
    marginBottom: 12,
    textAlign: "justify",
  },
  bioP: {
    color: "#d6d6d6",
    fontSize: 15,
    lineHeight: 1.5,
    marginBottom: 14,
  },
  skillGrid: {
    marginTop: 10,
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 14,
    alignItems: "start",
  },
  skillCard: {
    background: "#141414",
    border: "1px solid #232323",
    borderRadius: 10,
    padding: "10px 12px",
    marginBottom: "12px",
  },
  skillCategoryHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginBottom: 10,
  },
  skillCategoryLabel: {
    fontSize: 11,
    fontWeight: 700,
    color: "#a7a7a7",
    textTransform: "uppercase",
    letterSpacing: "0.6px",
  },
  chipRowCompact: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
  },
  skillChipSmall: {
    padding: "5px 11px",
    borderRadius: 12,
    background: "#1e1e1e",
    border: "1px solid #2a2a2a",
    fontSize: 11.5,
    color: "#d6d6d6",
    whiteSpace: "nowrap",
    transition: "all .15s ease",
  },
  secHead: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    padding: "12px 0 12px",
  },
  secH2: {
    fontSize: 23,
    fontWeight: 800,
    fontFamily: "Montserrat",
  },
  spotifyStateBox: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: 12,
    background: "#181818",
    borderRadius: 12,
    color: "#a7a7a7",
    fontSize: 13.5,
  },
  chipRow: {
    display: "flex",
    gap: 10,
    marginBottom: 20,
    flexWrap: "wrap",
  },
  chip: {
    padding: "8px 18px",
    borderRadius: 20,
    border: "1px solid #2a2a2a",
    background: "transparent",
    color: "#a7a7a7",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    fontFamily: "inherit",
    transition: "all .15s ease",
  },
  chipActive: {
    background: "#fff",
    color: "#000",
    border: "1px solid #fff",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 22,
    paddingBottom: 10,
  },
  card: {
    borderRadius: 8,
    padding: 10,
    cursor: "pointer",
    transition: "background .2s ease",
    overflow: "hidden",
    minWidth: 0,
    height: "300px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
  },
  cardCover: {
    width: "100%",
    aspectRatio: "16/9",
    borderRadius: 6,
    marginBottom: 14,
    position: "relative",
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 8px 24px rgba(0,0,0,.4)",
    transition: "transform .25s ease",
  },
  coverGlyph: {
    fontFamily: "Montserrat",
    fontWeight: 900,
    fontSize: 42,
    color: "rgba(255,255,255,.9)",
  },
  playOverlay: {
    position: "absolute",
    right: 8,
    bottom: 8,
    width: 40,
    height: 40,
    borderRadius: "50%",
    background: ACCENT,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "none",
    cursor: "pointer",
    boxShadow: "0 8px 16px rgba(0,0,0,.5)",
    opacity: 0,
    transform: "translateY(8px)",
    transition: "opacity .2s ease, transform .2s ease",
    zIndex: 2,
  },
  playOverlayVisible: {
    opacity: 1,
    transform: "translateY(0)",
  },
  playOverlayHover: {
    transform: "translateY(-4px)",
    boxShadow: "0 10px 22px rgba(0,0,0,.6)",
  },
  // === project preview modal ===
  emptyState: {
    padding: "48px 16px",
    textAlign: "center",
    color: "#727272",
    fontSize: 14,
  },
  backdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.72)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: 20,
  },
  closeBtn: {
    position: "absolute",
    top: 12,
    right: 12,
    zIndex: 2,
    width: 32,
    height: 32,
    borderRadius: "50%",
    border: "none",
    background: "rgba(0,0,0,0.55)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    transition: "background .15s ease",
  },
  closeBtnHover: {
    background: "rgba(0,0,0,0.8)",
  },
  modalPlayBtn: {
    position: "absolute",
    bottom: 16,
    right: 16,
    zIndex: 4,
    width: 48,
    height: 48,
    borderRadius: "50%",
    background: ACCENT,
    border: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: "0 6px 16px rgba(0,0,0,0.4)",
    transition: "transform .15s ease",
  },
  modalPlayBtnHover: {
    transform: "scale(1.06)",
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: "#fff",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    wordBreak: "break-word",
    lineHeight: 1.4,
    minHeight: "2.2em",
    marginTop: 4,
    marginBottom: 0,
  },
  cardDesc: {
    fontSize: 11,
    color: "rgba(255,255,255,0.6)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
    wordBreak: "break-word",
    lineHeight: 1.4,
    minHeight: "2.7em",
    textAlign: "left",
  },
  gridCert: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
    gap: 16,
    paddingBottom: 10,
  },
  certCard: {
    background: "#181818",
    borderRadius: 10,
    padding: 16,
    display: "flex",
    alignItems: "center",
    textAlign: "left",
    gap: 14,
  },
  certBadge: {
    width: 46,
    height: 46,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    boxShadow: "0 6px 16px rgba(0,0,0,.4)",
  },
  certTitle: {
    fontSize: 14,
    fontWeight: 700,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  certIssuer: {
    fontSize: 12.5,
    color: "#a7a7a7",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  certYear: {
    marginLeft: "auto",
    fontSize: 12,
    color: "#727272",
    flexShrink: 0,
  },
  ctaBanner: {
    borderRadius: 12,
    background: "linear-gradient(120deg, #123a20, #0d2818 55%, #0a1a10)",
    padding: "44px 48px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 24,
    position: "relative",
    overflow: "hidden",
  },
  ctaGlow: {
    position: "absolute",
    right: -60,
    top: -60,
    width: 260,
    height: 260,
    background: "radial-gradient(circle, rgba(29,185,84,.25), transparent 70%)",
  },
  ctaH2: {
    fontSize: 32,
    fontWeight: 900,
    marginBottom: 8,
    fontFamily: "Montserrat",
    textAlign: "justify",
  },
  ctaP: {
    color: "#a7a7a7",
    fontSize: 14.5,
    maxWidth: 420,
    textAlign: "justify",
  },
  footer: {
    padding: "48px 0 48px",
    color: "#727272",
    fontSize: 12,
    textAlign: "center",
  },

  timeLabel: {
    fontSize: 10.5,
    color: "#727272",
  },
  progressTrack: {
    flex: 1,
    height: 4,
    background: "#4d4d4d",
    borderRadius: 2,
    position: "relative",
    cursor: "pointer",
  },
  progressFill: {
    position: "absolute",
    left: 0,
    top: 0,
    height: "100%",
    background: ACCENT_BRIGHT,
    borderRadius: 2,
  },
  volTrack: {
    width: 90,
    height: 4,
    background: "#4d4d4d",
    borderRadius: 2,
    position: "relative",
  },
  volFill: {
    position: "absolute",
    left: 0,
    top: 0,
    height: "100%",
    width: "70%",
    background: "#fff",
    borderRadius: 2,
  },
  btnIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "rgba(29,185,84,0.08)",
    color: ACCENT_BRIGHT,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 0 0 1px rgba(29,185,84,0.35), 0 0 16px rgba(29,185,84,0.25)",
    cursor: "pointer",
    border: "none",
    textDecoration: "none",
    transition: "all .2s ease",
  },
  certCardClickable: {
    cursor: "pointer",
    transition: "background .2s ease, transform .15s ease",
  },
  certCardHover: {
    background: "#1f1f1f",
    transform: "translateY(-2px)",
  },
  certArrow: {
    flexShrink: 0,
    color: "#727272",
    opacity: 0,
    transform: "translateX(-4px)",
    transition: "opacity .2s ease, transform .2s ease",
  },
  certArrowVisible: {
    opacity: 1,
    transform: "translateX(0)",
  },

  // === cert preview modal ===
  certModalBody: {
    padding: "32px 28px 28px",
    textAlign: "center",
  },
  certModalBadge: {
    width: 76,
    height: 76,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 18px",
    boxShadow: "0 10px 24px rgba(0,0,0,.4)",
  },
  certModalTitle: {
    color: "#fff",
    fontSize: 19,
    fontWeight: 800,
    fontFamily: "Montserrat",
    margin: "0 0 6px",
  },
  certModalIssuer: {
    color: "#a7a7a7",
    fontSize: 14,
    marginBottom: 4,
  },
  certModalYear: {
    color: "#727272",
    fontSize: 12.5,
    marginBottom: 16,
  },
  certModalDesc: {
    color: "#d6d6d6",
    fontSize: 13.5,
    lineHeight: 1.6,
    marginBottom: 20,
    textAlign: "left",
  },
  certModalLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    background: "transparent",
    color: "#fff",
    fontWeight: 700,
    fontSize: 13.5,
    padding: "10px 22px",
    borderRadius: 24,
    border: "1px solid #2a2a2a",
    textDecoration: "none",
    transition: "all .2s ease",
  },
  certModalPreviewWrap: {
    width: "100%",
    aspectRatio: "4 / 3",
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 16,
    background: "#000",
  },
  certModalPreviewFrame: {
    width: "100%",
    height: "100%",
    border: "none",
  },
  awardList: {
    background: "#181818",
    borderRadius: 12,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  awardRow: {
    display: "grid",
    gridTemplateColumns: "28px 44px 1fr 200px 50px 20px",
    alignItems: "center",
    columnGap: 20,
    padding: "10px 14px",
    borderBottom: "1px solid #1f1f1f",
    transition: "background .15s ease",
  },
  awardOrg: {
    fontSize: 12,
    color: "#a7a7a7",
    textAlign: "left",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  awardRowLast: {
    borderBottom: "none",
  },
  awardRowHover: {
    background: "#1c1c1c",
  },
  awardIndex: {
    color: "#727272",
    fontSize: 14,
  },
  awardBadge: {
    width: 44,
    height: 44,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    boxShadow: "0 6px 16px rgba(0,0,0,.4)",
  },
  awardTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: "#fff",
    marginBottom: 3,
    textAlign: "left",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  awardDesc: {
    fontSize: 13.5,
    color: "#a7a7a7",
    textAlign: "left",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  awardYear: {
    fontSize: 13.5,
    color: "#727272",
    textAlign: "right",
  },
  awardRowClickable: {
    cursor: "pointer",
  },
  awardArrow: {
    flexShrink: 0,
    color: "#727272",
    opacity: 0,
    transform: "translateX(-4px)",
    transition: "opacity .2s ease, transform .2s ease",
  },
  awardArrowVisible: {
    opacity: 1,
    transform: "translateX(0)",
  },

  // === award preview modal ===
  awardModalBody: {
    padding: "32px 28px 28px",
    textAlign: "center",
  },
  awardModalBadge: {
    width: 76,
    height: 76,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 18px",
    boxShadow: "0 10px 24px rgba(0,0,0,.4)",
  },
  awardModalTitle: {
    color: "#fff",
    fontSize: 19,
    fontWeight: 800,
    fontFamily: "Montserrat",
    margin: "0 0 6px",
  },
  awardModalEvent: {
    color: "#a7a7a7",
    fontSize: 14,
    marginBottom: 4,
  },
  awardModalYear: {
    color: "#727272",
    fontSize: 12.5,
    marginBottom: 4,
  },
  awardModalDesc: {
    color: "#d6d6d6",
    fontSize: 14,
    margin: "4px 0px 20px 0px",
    textAlign: "center",
  },
  awardCardHover: {
    background: "#1f1f1f",
    transform: "translateY(-2px)",
  },
  ctaLayout: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    gap: 60,
    flexWrap: "wrap",
    alignItems: "flex-start",
  },
  ctaLeft: {
    flex: "1 1 260px",
    minWidth: 260,
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  ctaFormActions: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
  },
  ctaEmailBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    flex: "1 1 auto",
    padding: "12px 20px",
    borderRadius: 12,
    border: "1px solid rgba(255,255,255,0.25)",
    background: "transparent",
    color: "#fff",
    fontSize: 14,
    fontWeight: 500,
    textDecoration: "none",
    transition: "all 0.2s ease",
    cursor: "pointer",
    boxSizing: "border-box",
  },
  ctaFormCard: {
    flex: "1 1 340px",
    minWidth: 300,
    maxWidth: 440,
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 16,
    padding: 24,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  ctaSubmitBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    border: "none",
    flex: "1 1 auto",
  },
  contactFormGrid: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  contactInput: {
    width: "100%",
    padding: "12px 16px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.15)",
    background: "rgba(255,255,255,0.06)",
    color: "#fff",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  socialRow: {
    display: "flex",
    gap: 10,
    marginTop: 4,
  },
  socialIconBtn: {
    width: 38,
    height: 38,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    border: "1px solid rgba(255,255,255,0.2)",
    background: "rgba(255,255,255,0.06)",
    color: "#fff",
    transition: "all 0.2s ease",
  },
  socialIconBtnHover: {
    background: "#1DB954",
    borderColor: "#1DB954",
    color: "#000",
    transform: "translateY(-2px)",
  },
  contactStatusSuccess: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 14px",
    borderRadius: 10,
    background: "rgba(29,185,84,0.15)",
    color: "#1DB954",
    fontSize: 13,
  },
  contactStatusError: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 14px",
    borderRadius: 10,
    background: "rgba(255,80,80,0.15)",
    color: "#ff5050",
    fontSize: 13,
  },
  modalBackdrop: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.75)",
    backdropFilter: "blur(4px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: 20,
  },
  modal: {
    position: "relative",
    width: "min(880px, 100%)",
    maxHeight: "90vh",
    overflowY: "auto",
    background: "#181818",
    borderRadius: 14,
    boxShadow: "0 20px 60px rgba(0,0,0,0.5)",
    display: "flex",
    flexDirection: "column",
    textAlign: "justify",
  },
  modalCover: {
    position: "relative",
    width: "100%",
    aspectRatio: "16 / 8",
    overflow: "hidden",
    flexShrink: 0,
  },
  modalSlideImg: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "auto",
    objectFit: "cover",
    transition: "opacity .5s ease",
  },
  modalGlyph: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 64,
  },
  modalNavBtn: {
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 3,
    width: 36,
    height: 36,
    borderRadius: "50%",
    border: "none",
    background: "rgba(0,0,0,0.5)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  modalDotsRow: {
    position: "absolute",
    bottom: 14,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    gap: 6,
    zIndex: 3,
  },
  modalDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    border: "none",
    background: "rgba(255,255,255,0.45)",
    cursor: "pointer",
    padding: 0,
    transition: "background .2s ease, transform .2s ease",
  },
  modalDotActive: {
    background: "#fff",
    transform: "scale(1.3)",
  },
  modalBody: {
    padding: "24px 28px 28px",
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: 700,
    margin: "10px 0 8px",
    color: "#fff",
  },
  modalDesc: {
    fontSize: 14.5,
    lineHeight: 1.6,
    color: "#b3b3b3",
    margin: 0,
  },
  modalFooter: {
    marginTop: 18,
  },
  modalLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "#1db954",
    fontWeight: 600,
    fontSize: 14,
    textDecoration: "none",
  },
  // === Modal body sections ===
  modalSection: {
    paddingTop: 14,
    borderTop: "1px solid rgba(255,255,255,0.08)",
  },
  modalSectionLabel: {
    display: "block",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: ACCENT,
    marginBottom: 6,
  },
  // === Modal body sections ===
  modalBodyCol: {
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  modalTitleSection: {
    fontSize: 22,
    fontWeight: 700,
    margin: 0,
    color: "#fff",
    lineHeight: 1.3,
  },
  modalSection: {
    paddingTop: 16,
    borderTop: "1px solid rgba(255,255,255,0.08)",
  },
  modalSectionLabelRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  modalSectionLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#727272",
  },
  modalDescText: {
    fontSize: 14.5,
    lineHeight: 1.7,
    color: "#b3b3b3",
    margin: 0,
  },
  modalRoleBadge: {
    display: "inline-block",
    fontSize: 12.5,
    fontWeight: 600,
    letterSpacing: 0.3,
    color: "#1db954",
    background: "rgba(29,185,84,0.12)",
    padding: "5px 12px",
    borderRadius: 999,
  },
  modalTechRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  modalTechChip: {
    fontSize: 12,
    fontWeight: 600,
    padding: "5px 11px",
    borderRadius: 999,
    background: "#232323",
    border: "1px solid rgba(255,255,255,0.08)",
    color: "#b3b3b3",
  },
  modalFooterSpaced: {
    marginTop: 4,
  },
  modalLinkBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    color: "#000",
    background: "#1db954",
    fontWeight: 700,
    fontSize: 14,
    textDecoration: "none",
    padding: "10px 18px",
    borderRadius: 999,
    transition: "background .15s ease, transform .15s ease",
  },
  projectLinksRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginTop: 12,
    paddingTop: 10,
    borderTop: "1px solid rgba(255,255,255,0.06)",
  },
  projectIconBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 20,
    height: 20,
    color: "#727272",
    transition: "color .15s ease, transform .15s ease",
  },
  projectIconBtnHover: {
    color: "#1db954",
    transform: "translateY(-1px)",
  },
  timelineWrap: {
    position: "relative",
    marginTop: 24,
    paddingLeft: 28,
  },
  timelineLine: {
    position: "absolute",
    left: 5,
    top: 6,
    bottom: 6,
    width: 2,
    background: "rgba(255,255,255,0.08)",
  },
  timelineItem: {
    position: "relative",
    paddingBottom: 32,
  },
  timelineDot: {
    position: "absolute",
    left: -28,
    top: 4,
    width: 12,
    height: 12,
    borderRadius: "50%",
    background: "#1db954",
    border: "3px solid #121212",
    boxShadow: "0 0 0 2px rgba(29,185,84,0.25)",
  },
  timelineCard: {
    background: "#181818",
    borderRadius: 12,
    padding: "18px 20px",
    textAlign: "justify",
    transition: "background .15s ease, border-color .15s ease",
  },
  timelineCardHover: {
    background: "#1f1f1f",
  },
  timelineHeadRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
    gap: 8,
  },
  timelineRole: {
    fontSize: 16,
    fontWeight: 700,
    color: "#fff",
    margin: 0,
  },
  timelineCompany: {
    fontSize: 13,
    color: "#1db954",
    fontWeight: 600,
    marginTop: 2,
  },
  timelinePeriod: {
    fontSize: 12,
    color: "#727272",
    fontWeight: 600,
    whiteSpace: "nowrap",
    background: "#232323",
    padding: "4px 10px",
    borderRadius: 999,
  },
  timelineLocation: {
    fontSize: 12,
    color: "#727272",
    marginTop: 4,
  },
  timelineDesc: {
    fontSize: 13.5,
    lineHeight: 1.6,
    color: "#b3b3b3",
    marginTop: 12,
  },
  timelineTechRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 12,
  },
};